### ISSUE TITLE
Not detecting camera on demo site

### ISSUE THREAD

**Issue by udaraeshan** [id1945/ngx-scanner-face#4]
Hi, I have tried the demo, but not detecting the web camera.
can you help me with this?

![Screenshot 2023-03-08 091503](https://user-images.githubusercontent.com/20475566/223614665-97d2932d-ec8d-4e45-8f2d-dc7cbd0c72e5.png)

**Comment by id1945** [comment]
@udaraeshan I understood why it failed

**Comment by id1945** [comment]
@udaraeshan I fixed it in version 1.1.5
