### ISSUE TITLE
How to convert face area detection to base64?

### ISSUE THREAD

**Issue by larnerdoj** [id1945/ngx-scanner-face#5]
**Hello DaiDH!**
How are you?

I'm using ngx-scanner-face to perform face detection and send to an external api.
Is it possible to get the data in **base64** and send it to an external api?

**Comment by id1945** [comment]
@larnerdoj I'm fine @@
Currently canvas version 1.1.5 contains only the original image.
I will upgrade to the new version and release canvas for you to convert to base64.
In the next few days, stay tuned.

**Comment by larnerdoj** [comment]
Woww great news!!
I'll be waiting
Thank you very much man!
